import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 15000

[window]
opacity = 1.0

[window.dimensions]
columns = 100
lines = 24
